### ISSUE TITLE
login loop

### ISSUE THREAD

**Issue by chrissix666** [bartok765/galaxy_blizzard_plugin#35] opened 2020-08-06 18:26 UTC
I can successful login into the Battle.net, but after the login window closes ist states "offline - retry", i open the window again and can login.

- Login successful
- But the plugin always left behind "offline - retry"

I also deinstalled and re-installed the plugin several times, without success

**Comment by elkangaroo** [comment] 2020-08-06 19:04
Thanks for your report @chrissix666, can you please check if there is any errors in the log file? You can find it here:
- Windows: `%programdata%\GOG.com\Galaxy\logs\plugin-battlenet-*.log`
- MacOS: `/Users/Shared/GOG.com/Galaxy/Logs/plugin-battlenet-*.log`

**Comment by EnderXH** [comment] 2020-08-06 21:40
Same issue here. I have no errors in the logs, which is odd.
I'll attach the log , maybe it will be useful.
[plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log](https://github.com/bartok765/galaxy_blizzard_plugin/files/5038143/plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log)

**Comment by Tvdv013** [comment] 2020-08-07 12:06
I'm having the same issue
[plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log](https://github.com/bartok765/galaxy_blizzard_plugin/files/5041237/plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log)

**Comment by Gliptal** [comment] 2020-08-07 13:47
Same issue here.
[plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log](https://github.com/bartok765/galaxy_blizzard_plugin/files/5041740/plugin-battlenet-ba170431-0649-482f-863b-d248592f1842.log)

**Comment by elkangaroo** [comment] 2020-08-07 17:13
Thanks for the log files, the "Backend timed out" is indeed causing this issue).
I am investigating now.

**Comment by elkangaroo** [comment] 2020-08-07 17:58
The problem is, after login we send a request to https://eu.account.blizzard.com:443/oauth2/authorization/account-settings which currently times out (almost) always. Timeout is 10 seconds.
I could even reproduce it once on offical battle.net website after login. There seems to be some issues on blizzard servers.

@bartok765 As a workaround I increased the timeout in #36, do you think we can use this as a quick fix?

**Comment by bartok765** [comment] 2020-08-07 20:57
Yes, definitely. Is 20sec long enough?

**Comment by elkangaroo** [comment] 2020-08-07 21:27
In my tests it was mostly around ~11seconds

bartok765 <notifications@github.com> schrieb am Fr., 7. Aug. 2020, 22:57:

**Comment by bartok765** [comment] 2020-08-07 21:42
Merged. Just tried myself, and one time is below 10, another time more than 10.
I've pushed 1.3.1 version to `fog_release` branch. Leaving the issue open until @FriendsOfGalaxy merge it. Thanks @elkangaroo for quick check.

**Comment by chrissix666** [comment] 2020-08-08 13:18
I have no idea how to update the plugin myself (not a noob but less github experienced)

I just closed Gog Galaxy 2.0 & exchanged the 2 files you updated:
backend.py
http_client.py

Unfortunately it does not change anything, issue still persits.
Looking forward to an official bug fix realease

**Comment by bartok765** [comment] 2020-08-08 15:12
@chrissix666 what you've done should work. Drop your logs please - maybe there is different problem.

**Comment by bartok765** [comment] 2020-08-08 20:44
Update: I've doubled timeout to 40s as it was not enough for me today.

**Comment by Gliptal** [comment] 2020-08-08 22:11
I can confirm the latest 40s change fixes the problem.

**Comment by chrissix666** [comment] 2020-08-09 00:01
I can also confirm with the latest changes login is possble again with success. Great thanks, much appreciated!

**Closed** 2020-08-10 17:56 UTC
